env:
  browser: true
  es6: true
  node: true
  jest/globals: true
parser: "@typescript-eslint/parser"
plugins:
  - "@typescript-eslint"
  - "jest"
  - "playwright"
parserOptions:
  ecmaVersion: latest
  sourceType: module
  ecmaFeatures:
    modules: true
  project: true
extends:
  - "eslint:recommended"
rules:
  no-const-assign: error
  no-duplicate-imports: error
  no-unreachable: error
  no-unused-vars: off
  "@typescript-eslint/no-unused-vars":
    - error
    - argsIgnorePattern: "^_"
  no-console: error
  no-empty: error
  no-extra-semi: error
  multiline-comment-style: off

overrides:
  - files:
      - "tests/**/*"
      - "cli/**"
      - "deployment/**"
    rules:
      no-console: off
